name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Gradlew permissions
      - name: Give gradlew permissions
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configuración de Gradle con cache
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Compilación + tests + REPORTE + VALIDACIÓN
      - name: Build and Verify Coverage
        run: ./gradlew clean build jacocoTestCoverageVerification
        
      # Sube el reporte HTML (sigue siendo útil)
      - name: Upload JaCoCo HTML Report for Debugging
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: jacoco-html-report
          path: build/reports/jacoco/test/html/
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
          
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
