name: Java CI with Gradle

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Gradlew permissions
      - name: Give gradlew permissions
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Instalar Firefox con la acci贸n oficial (versi贸n normal)
      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      # Instalar GeckoDriver (driver de Firefox)
      - name: Set up GeckoDriver
        uses: browser-actions/setup-geckodriver@latest

      # Exportar variables de entorno para Selenium
      - name: Export FIREFOX_BIN and GECKO_DRIVER_PATH
        shell: bash
        run: |
          echo "FIREFOX_BIN=$(command -v firefox)" >> $GITHUB_ENV
          echo "GECKO_DRIVER_PATH=$(command -v geckodriver)" >> $GITHUB_ENV

      # Configuraci贸n de Gradle con cache
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      
      # Compilaci贸n + tests
      - name: Build with Gradle Wrapper
        run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
